[[arrows]]
click_time = 5.3191767
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 5.6455599
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 6.2006796
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 6.818609
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 7.4992653
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 8.22836
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 8.8124171
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 9.2287954
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 9.7355033
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 10.0410477
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 10.6659347
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 10.6799968
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 12.0064804
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 12.5686884
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 13.1312709
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 13.7084394
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 13.7495101
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 14.1797875
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 14.2631993
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 14.2771309
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 14.6935973
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 15.0270968
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 15.3880904
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 15.6312647
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 16.270021
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 16.5132
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 16.7909597
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 17.4019761
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 17.4019761
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 17.7355466
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 18.0270599
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 18.3672272
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 18.6728924
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 18.6728924
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 19.971443999999998
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 19.9782887
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 20.2285634
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 20.5338085
speed = "Slow"
direction = "Down"

[[arrows]]
click_time = 21.1797021
speed = "Slow"
direction = "Left"

[[arrows]]
click_time = 21.4087341
speed = "Slow"
direction = "Right"

[[arrows]]
click_time = 21.707311699999998
speed = "Slow"
direction = "Up"

[[arrows]]
click_time = 22.3671804
speed = "Slow"
direction = "Down"
